spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: ksppsk
    url: jdbc:postgresql://localhost:5432/test
    username: valentin
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: pass
    key-store-type: PKCS12
    key-alias: tomcat
  port: 8443
  error:
    whitelabel:
      enabled: false