file:
  upload-dir: ${user.home}/task-manager-api/uploads
spring:
  messages:
    basename: messages,validation-messages
    encoding: UTF-8
    cache-duration: 1h
  cache:
    cache-names: taskTypes
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h
    type: caffeine
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    hikari:
      connectionTimeout: ${DB_CONNECTION_TIMEOUT}
      maximumPoolSize: ${DB_POOL_SIZE}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
