file:
  upload-dir: ${user.home}/task-manager-api/uploads
spring:
  messages:
    basename: messages,validation-messages
    encoding: UTF-8
    cache-duration: 1h
  cache:
    cache-names: taskTypes
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h
    type: caffeine
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret: 0e26b72fe43bc06f1145af24a33e88ff624aff1abf1bef6f856bbb0cc04f17d3
  expiration: 600000