spring:
  datasource:
    hikari:
      connectionTimeout: ${DB_CONNECTION_TIMEOUT}
      maximumPoolSize: ${DB_POOL_SIZE}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: pass
    key-store-type: PKCS12
    key-alias: tomcat
  port: 8443